substitutions:
  _REGION: us-central1
  _REPO: demo-app
  _IMAGE: demo-app
  _CLUSTER: demo-cluster

steps:
  # ── 1. Build Docker image ────────────────────────────────────────────────
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$SHORT_SHA
      - --tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:latest
      - --build-arg=APP_VERSION=$SHORT_SHA
      - --cache-from=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:latest
      - ./app

  # ── 2. Push to Artifact Registry ────────────────────────────────────────
  - id: push-sha
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$SHORT_SHA

  - id: push-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:latest

  # ── 3. Get GKE credentials ───────────────────────────────────────────────
  - id: get-credentials
    name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - $_CLUSTER
      - --region=$_REGION
      - --project=$PROJECT_ID

  # ── 4. Deploy to GKE ────────────────────────────────────────────────────
  - id: deploy
    name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - set
      - image
      - deployment/demo-app
      - demo-app=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$SHORT_SHA
      - --namespace=default

  # ── 5. Wait for rollout ──────────────────────────────────────────────────
  - id: rollout-status
    name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
    args:
      - rollout
      - status
      - deployment/demo-app
      - --timeout=3m

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 900s  # 15 min total timeout